services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: manzione_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ../client
    ports:
      - "5173:80"

volumes:
  db_data:
